### ISSUE TITLE
Boleto BB - Com registro, convênio com 7 posições!

### ISSUE THREAD

**Issue by LeandroFranciscato** [jrimum/bopepo#27]
Olá Pessoal.
Primeiramente, que projeto sensacional, parabéns.
Segundamente, só gostaria de confirmar se [este exemplo](http://jrimum.org/bopepo/wiki/Componente/Documentacao/Tutoriais/Bancos/BB/NossoNumero17Convenio7) pode ser utilizado para geração de boletos do BB COM REGISTRO.

Obrigado desde já!

**Comment by jeroqueiroz** [comment]
A questão do Registro esta na forma que você preenche o Boleto. O Exemplo não esta com a parte de Registro, mas você pode adequar pois a biblioteca tem disponível o necessário para que seja registrado o boleto. Na verdade a questão de ser registrado ou não esta ligado a informações que são preenchidas no boleto.

**Comment by LeandroFranciscato** [comment]
Obrigado pela resposta @jeroqueiroz.
Você tem razão, notei que ao criar a carteira ````contaBancaria.setCarteira(new Carteira(23));````eu posso informar o  ````TipoDeCobrança````, que é um enum com as possibilidades ````COM_REGISTRO```` e ````SEM_REGISTRO````.
A minha dúvida surgiu porque o banco me questionou quanto à composição do código de barras. O que disseram foi o seguinte:

**> Código de Barras e Linha Digitavel**
> Utilizar anexo IX (pagina 20) do Manual de para confecção de boletos (segue anexo) para montagem do Código de Barras e consequente reformulação da Linha Digitavel.
> Indevidamente foi utilizado o anexo X (pagina 21).

O que posso estar fazendo de errado?

**Segue manual**
[Manual confecções de boletos.pdf](https://github.com/jrimum/bopepo/files/611323/Manual.confeccoes.de.boletos.pdf)

**Comment by jeroqueiroz** [comment]
Melhor voce utilizar o fórum pra tirar estas duvidas: https://groups.google.com/forum/#!forum/jrimum-community

**Comment by jeroqueiroz** [comment]
Posta lá no fórum que terá mais respostas.

**Comment by LeandroFranciscato** [comment]
Ok. Obrigado @jeroqueiroz
